[client]
toolbarMode = "minimal"
showErrorDetails = "full"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1769AA"
linkColor = "#1769AA"
blueColor = "#1769AA"
blueBackgroundColor = "#E6F2FF"
blueTextColor = "#0C447C"
font = "sans-serif"
headingFont = "sans-serif"
baseFontSize = 16
baseFontWeight = 400
headingFontWeights = [700, 700, 600, 600, 600, 600]
