const status=document.querySelector('#privacy-status'),content=document.querySelector('#privacy-content'),list=document.querySelector('#privacy-request-list');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={access:'Data copy',correction:'Correction',deletion:'Deletion / account closure'};
async function request(url,options={}){const response=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json'}});const data=await response.json();if(!response.ok){const error=new Error(typeof data.detail==='string'?data.detail:'Could not complete this request');error.status=response.status;throw error}return data}
async function load(){
 status.textContent='Loading requests…';
 try{const data=await request('/api/privacy-requests');content.hidden=false;
 document.querySelector('#request-heading').textContent=data.owner?'Owner review queue':'Your requests';
 document.querySelector('#request-list-note').textContent='Showing the latest 200 requests. Status and responses update here; no automatic email is sent.';
 list.innerHTML=data.requests.map(row=>`<article class="privacy-request"><h3>${escape(names[row.kind]||row.kind)}</h3><p><strong>${escape(row.status)}</strong> · ${escape(new Date(row.created_at).toLocaleDateString())}</p><small>Reference: ${escape(row.id)}</small>${data.owner?`<p>${escape(row.email)}</p>`:''}<p class="preserve-lines">${escape(row.details||'No additional details supplied.')}</p>${row.response?`<p class="privacy-response preserve-lines"><strong>Owner response</strong><br>${escape(row.response)}</p>`:''}${data.owner?`<form data-review="${escape(row.id)}"><label>Request status<select name="status"><option value="reviewing">Reviewing</option><option value="completed">Completed</option><option value="declined">Declined</option></select></label><label>Response visible to the requester<textarea name="response" rows="3" maxlength="2000">${escape(row.response||'')}</textarea></label><p>Complete only after the requested work is done. Changing this status does not delete or export data.</p><button type="submit">Save review</button></form>`:''}</article>`).join('')||'<p>No requests yet.</p>';
 if(data.owner)list.querySelectorAll('[data-review]').forEach(form=>{const row=data.requests.find(r=>r.id===form.dataset.review);form.elements.status.value=row.status==='received'?'reviewing':row.status;form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await request('/api/owner/privacy-requests/'+encodeURIComponent(form.dataset.review),{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await load();status.textContent='Review saved.'}catch(error){status.textContent=error.message}finally{button.disabled=false}}});
 status.textContent='Requests loaded.';
 }catch(error){if(error.status===401){content.hidden=true;status.innerHTML='Sign in with your candidate or owner account, then return here. <a href="/?candidate=1">Candidate sign-in</a> · <a href="/?owner=1">Owner sign-in</a>'}else status.textContent=error.message+' You can also use the privacy contact below.'}
}
document.querySelector('#privacy-request-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;try{const row=await request('/api/privacy-requests',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await load();status.textContent='Request saved. Reference: '+row.id}catch(error){status.textContent=error.message}finally{button.disabled=false}};
document.querySelector('#refresh-privacy').onclick=load;
load();
