// Add notices and accessible names without changing existing form submissions.
let serial=0,scheduled=false;
let lastOutsideFocus=document.activeElement;
document.addEventListener('focusin',event=>{if(!event.target.closest('.modal-shell'))lastOutsideFocus=event.target});
const activeDialogs=new Map();
function notice(form,text){if(!form||form.querySelector('[data-trust-notice]'))return;const p=document.createElement('p');p.className='trust-notice';p.dataset.trustNotice='';p.innerHTML=text;form.append(p)}
function enhance(){
 const owner=document.querySelector('.owner-portal');if(owner&&!owner.querySelector('.owner-actions')){const panel=document.createElement('section');panel.className='owner-actions';panel.setAttribute('aria-label','Actions needing attention');owner.querySelector('.owner-hero')?.after(panel);loadOwnerActions(panel)}
 const screen=document.querySelector('.screen-status');if(screen){screen.setAttribute('role','status');screen.setAttribute('aria-live','polite');const form=document.querySelector('#screen-form'),busy=!!form?.querySelector('button[type="submit"]:disabled,.screen-submit:disabled');if(form)form.setAttribute('aria-busy',String(busy));if(busy&&!form.querySelector('.screen-wait-note')){const note=document.createElement('p');note.className='screen-wait-note trust-notice';note.textContent='Screening is running. Larger batches take longer. Keep this page open and avoid submitting the same batch again.';screen.after(note)}if(!busy)form?.querySelector('.screen-wait-note')?.remove()}
 const interviewList=document.querySelector('.interview-list');if(interviewList&&!interviewList.dataset.deliveryEnhanced){interviewList.dataset.deliveryEnhanced='1';const refresh=document.createElement('button');refresh.type='button';refresh.className='secondary';refresh.textContent='Refresh email status';interviewList.prepend(refresh);refresh.onclick=()=>loadDeliveries(interviewList,refresh);loadDeliveries(interviewList,refresh)}
 document.querySelectorAll('label').forEach(label=>{if(label.htmlFor||label.querySelector('input,select,textarea'))return;const next=label.nextElementSibling;if(next?.matches('input,select,textarea')){next.id=next.id||`accessible-field-${++serial}`;label.htmlFor=next.id}});
 notice(document.querySelector('#registration-form'),'ICD is a free recruitment prototype intended for adults aged 18 and over. We use these details to review your organization. Please provide only business information you are authorized to share. <a href="/privacy" target="_blank" rel="noopener">Privacy policy</a> · <a href="/terms" target="_blank" rel="noopener">Terms</a>.');
 notice(document.querySelector('#screen-form'),'Upload only résumés you are authorized to process. Relevant résumé text and job requirements may be processed by configured AI providers. Review the evidence before making a hiring decision. <a href="/privacy" target="_blank" rel="noopener">How data is used</a>.');
 const host=document.querySelector('.owner-nav')||document.querySelector('.candidate-portal header');
 if(host&&!host.querySelector('[data-privacy-center]')){const a=document.createElement('a');a.href='/privacy-center';a.className='privacy-link';a.dataset.privacyCenter='';a.textContent='Privacy requests';host.append(a)}
 const dialogs=[...document.querySelectorAll('.modal-shell')];
 for(const shell of dialogs){if(activeDialogs.has(shell))continue;const dialog=shell.querySelector('[role="dialog"],section,form');if(!dialog)continue;activeDialogs.set(shell,lastOutsideFocus);dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');const h=dialog.querySelector('h1,h2,h3');if(h){h.id=h.id||`accessible-dialog-${++serial}`;dialog.setAttribute('aria-labelledby',h.id)}}
 for(const [shell,opener]of activeDialogs){if(shell.isConnected)continue;activeDialogs.delete(shell);if(!dialogs.length&&opener?.isConnected&&!opener.closest('.modal-shell'))opener.focus({preventScroll:true})}
}
document.addEventListener('keydown',event=>{const shell=[...document.querySelectorAll('.modal-shell')].filter(e=>!e.hidden&&e.getClientRects().length).at(-1);if(!shell)return;
 const items=[...shell.querySelectorAll('button,a[href],input:not([type=hidden]),select,textarea,[tabindex]')].filter(e=>!e.disabled&&e.tabIndex>=0&&e.getClientRects().length);
 if(event.key==='Escape'){const close=shell.querySelector('.modal-close,[data-close-questions]');if(close){event.preventDefault();close.click()}}
 if(event.key==='Tab'&&items.length){const first=items[0],last=items.at(-1);if(!shell.contains(document.activeElement)){event.preventDefault();first.focus()}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
});
new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;enhance()})}).observe(document.body,{childList:true,subtree:true});
enhance();

async function loadDeliveries(container,refresh){
 refresh.disabled=true;
 try{const response=await fetch('/api/interview-deliveries');if(!response.ok)throw new Error('Email status unavailable');const rows=await response.json();
 container.querySelectorAll('[data-delivery-state]').forEach(e=>e.remove());
 for(const row of rows){const card=[...container.querySelectorAll('[data-interview-status]')].find(e=>e.dataset.interviewStatus===String(row.interview_id))?.closest('.interview-card');if(!card)continue;
 const box=document.createElement('div');box.className='trust-notice delivery-state';box.dataset.deliveryState=row.status;const label={sent:'Sent · Accepted by the email service',failed:'Failed · Invitation needs attention',queued:'Waiting · Invitation queued',sending:'Unconfirmed · Sending or awaiting confirmation'};const heading=document.createElement('strong');heading.textContent=label[row.status]||'Delivery status unavailable';box.append(heading);const stamp=document.createElement('small');stamp.textContent=row.updated_at?'Updated '+new Date(row.updated_at).toLocaleString():'Update time unavailable';box.append(stamp);
 if(['failed','queued'].includes(row.status)){const retry=document.createElement('button');retry.type='button';retry.className='secondary';retry.textContent='Retry invitation';retry.onclick=async()=>{if(!confirm('Retry this interview invitation? Check whether the candidate already received it to avoid duplicate emails.'))return;retry.disabled=true;try{const r=await fetch('/api/interview-deliveries/'+encodeURIComponent(row.id)+'/retry',{method:'POST'});if(!r.ok){const data=await r.json();throw new Error(data.detail||'Retry unavailable')}box.textContent='Retry queued. Refresh email status shortly.'}catch(error){box.textContent=error.message}};box.append(document.createElement('br'),retry)}
 if(row.status==='sending'){const text=document.createElement('p');text.textContent='Refresh shortly. If this persists, check with the candidate before sending another invitation.';box.append(text)}card.append(box)}
 refresh.textContent='Refresh email status';
 }catch(_){container.querySelectorAll('[data-delivery-state]').forEach(e=>e.remove());refresh.textContent='Email status unavailable · Retry'}finally{refresh.disabled=false}
}

async function loadOwnerActions(panel){
 panel.setAttribute('aria-busy','true');panel.innerHTML='<h2>Needs your attention</h2><p role="status">Checking approvals, privacy requests and invitation delivery…</p>';
 try{const response=await fetch('/api/owner/actions');if(!response.ok)throw new Error();const data=await response.json();if(!['pending_approvals','open_privacy_requests','delivery_issues'].every(k=>Number.isInteger(data[k])&&data[k]>=0))throw new Error();
 panel.innerHTML='<div class="owner-actions-heading"><div><span class="prototype-label">Prototype workspace</span><h2>Needs your attention</h2></div><button type="button" class="secondary" data-refresh-actions>Refresh actions</button></div><div class="owner-action-grid"></div><details class="owner-delivery-review" id="owner-delivery-review"><summary>Review invitation issues</summary><p>These invitations failed or have remained waiting/unconfirmed for over 10 minutes. Ask the company recruiter to open Interviews and review email status. Unconfirmed deliveries should be checked with the candidate before resending.</p><div data-delivery-review></div></details>';
 const items=[['pending_approvals','Organization approvals','#owner-review','Review requests'],['open_privacy_requests','Open privacy requests','/privacy-center','Open request queue'],['delivery_issues','Invitation issues','#owner-delivery-review','Review delivery issues']];
 for(const [key,label,href,action]of items){const a=document.createElement('a');a.className='owner-action-card';a.href=href;const count=document.createElement('strong');count.textContent=data[key];const name=document.createElement('span');name.textContent=label;const next=document.createElement('b');next.textContent=action+' →';a.append(count,name,next);if(key==='delivery_issues')a.onclick=()=>{panel.querySelector('details').open=true};panel.querySelector('.owner-action-grid').append(a)}
 const list=panel.querySelector('[data-delivery-review]');for(const row of data.deliveries||[]){const item=document.createElement('p');item.className='owner-delivery-row';const company=document.createElement('strong');company.textContent=row.company_name;const detail=document.createElement('span');detail.textContent=({failed:'Failed',queued:'Waiting',sending:'Unconfirmed'}[row.status]||'Check status')+' · '+new Date(row.updated_at).toLocaleString();item.append(company,detail);list.append(item)}if(!(data.deliveries||[]).length)list.textContent='No delivery issues reported.';else {const note=document.createElement('small');note.textContent='Showing up to 20 oldest issues. The total above includes all issues.';list.append(note)}
 panel.querySelector('[data-refresh-actions]').onclick=()=>loadOwnerActions(panel);
 }catch(_){panel.innerHTML='<h2>Needs your attention</h2><p role="status">The action summary could not be loaded. Approvals and privacy requests remain available from the navigation.</p><button type="button" class="secondary">Retry action summary</button>';panel.querySelector('button').onclick=()=>loadOwnerActions(panel)}finally{panel.setAttribute('aria-busy','false')}
}
